import styles from '@/styles/Home.module.css'

import Head from 'next/head'

import { Cinzel } from 'next/font/google'
import SideBar from '@/components/SideBar'

const font = Cinzel({ subsets: ['latin'], weight: ['400'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Criador de Site</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${font.className}`}>
                <h1>Criador de Site</h1>
                <SideBar />
            </main>
        </>
    )
}
