import styles from '@/styles/Home.module.css'

import { Phudu } from 'next/font/google'

import Head from 'next/head'

import SideBar from '@/components/SideBar'
import Display from '@/components/Display'

const font = Phudu({ subsets: ['latin'], weight: ['400'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Criador de Site</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${font.className}`}>
                <SideBar />
                <Display />
            </main>
        </>
    )
}
